#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v12
# autospec commit: a5d3013703f5
#
Name     : chafa
Version  : 1.14.1
Release  : 2
URL      : https://github.com/hpjansson/chafa/releases/download/1.14.1/chafa-1.14.1.tar.xz
Source0  : https://github.com/hpjansson/chafa/releases/download/1.14.1/chafa-1.14.1.tar.xz
Summary  : Image to character art facsimile
Group    : Development/Tools
License  : GPL-3.0 LGPL-3.0 MIT Zlib
Requires: chafa-bin = %{version}-%{release}
Requires: chafa-lib = %{version}-%{release}
Requires: chafa-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : docbook-xml
BuildRequires : file
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : librsvg-dev
BuildRequires : libxml2-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(libavif)
BuildRequires : pkgconfig(libtiff-4)
BuildRequires : pkgconfig(libwebp)
BuildRequires : pkgconfig(libwebpdemux)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Chafa
=====
Chafa is a command-line utility that converts image data, including
animated GIFs, into graphics formats or ANSI/Unicode character art suitable
for display in a terminal. It has broad feature support, allowing it to be
used on devices ranging from historical teleprinters to modern terminal
emulators and everything in between.

%package bin
Summary: bin components for the chafa package.
Group: Binaries
Requires: chafa-license = %{version}-%{release}

%description bin
bin components for the chafa package.


%package dev
Summary: dev components for the chafa package.
Group: Development
Requires: chafa-lib = %{version}-%{release}
Requires: chafa-bin = %{version}-%{release}
Provides: chafa-devel = %{version}-%{release}
Requires: chafa = %{version}-%{release}

%description dev
dev components for the chafa package.


%package doc
Summary: doc components for the chafa package.
Group: Documentation

%description doc
doc components for the chafa package.


%package lib
Summary: lib components for the chafa package.
Group: Libraries
Requires: chafa-license = %{version}-%{release}

%description lib
lib components for the chafa package.


%package license
Summary: license components for the chafa package.
Group: Default

%description license
license components for the chafa package.


%prep
%setup -q -n chafa-1.14.1
cd %{_builddir}/chafa-1.14.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719613740
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1719613740
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/chafa
cp %{_builddir}/chafa-%{version}/COPYING %{buildroot}/usr/share/package-licenses/chafa/31a3d460bb3c7d98845187c716a30db81c44b615 || :
cp %{_builddir}/chafa-%{version}/COPYING.LESSER %{buildroot}/usr/share/package-licenses/chafa/a8a12e6867d7ee39c21d9b11a984066099b6fb6b || :
cp %{_builddir}/chafa-%{version}/libnsgif/COPYING %{buildroot}/usr/share/package-licenses/chafa/91664a5e5a2b5bf020a621d0e9c5cc507e619c94 || :
cp %{_builddir}/chafa-%{version}/lodepng/LICENSE %{buildroot}/usr/share/package-licenses/chafa/7f11c0b5bfdf1146144bd11ce39af61c8296bc86 || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/chafa

%files dev
%defattr(-,root,root,-)
/usr/include/chafa/chafa-canvas-config.h
/usr/include/chafa/chafa-canvas.h
/usr/include/chafa/chafa-common.h
/usr/include/chafa/chafa-features.h
/usr/include/chafa/chafa-frame.h
/usr/include/chafa/chafa-image.h
/usr/include/chafa/chafa-placement.h
/usr/include/chafa/chafa-symbol-map.h
/usr/include/chafa/chafa-term-db.h
/usr/include/chafa/chafa-term-info.h
/usr/include/chafa/chafa-term-seq-def.h
/usr/include/chafa/chafa-util.h
/usr/include/chafa/chafa-version-macros.h
/usr/include/chafa/chafa.h
/usr/lib64/chafa/include/chafaconfig.h
/usr/lib64/libchafa.so
/usr/lib64/pkgconfig/chafa.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/chafa/api-index-deprecated.html
/usr/share/gtk-doc/html/chafa/api-index-full.html
/usr/share/gtk-doc/html/chafa/ch01.html
/usr/share/gtk-doc/html/chafa/ch02.html
/usr/share/gtk-doc/html/chafa/chafa-ChafaCanvas.html
/usr/share/gtk-doc/html/chafa/chafa-ChafaCanvasConfig.html
/usr/share/gtk-doc/html/chafa/chafa-ChafaFrame.html
/usr/share/gtk-doc/html/chafa/chafa-ChafaImage.html
/usr/share/gtk-doc/html/chafa/chafa-ChafaPlacement.html
/usr/share/gtk-doc/html/chafa/chafa-ChafaSymbolMap.html
/usr/share/gtk-doc/html/chafa/chafa-ChafaTermDb.html
/usr/share/gtk-doc/html/chafa/chafa-ChafaTermInfo.html
/usr/share/gtk-doc/html/chafa/chafa-Features.html
/usr/share/gtk-doc/html/chafa/chafa-Miscellaneous.html
/usr/share/gtk-doc/html/chafa/chafa-building.html
/usr/share/gtk-doc/html/chafa/chafa-using.html
/usr/share/gtk-doc/html/chafa/chafa.devhelp2
/usr/share/gtk-doc/html/chafa/home.png
/usr/share/gtk-doc/html/chafa/index.html
/usr/share/gtk-doc/html/chafa/left-insensitive.png
/usr/share/gtk-doc/html/chafa/left.png
/usr/share/gtk-doc/html/chafa/new-api-index-1.10.html
/usr/share/gtk-doc/html/chafa/new-api-index-1.12.html
/usr/share/gtk-doc/html/chafa/new-api-index-1.14.html
/usr/share/gtk-doc/html/chafa/new-api-index-1.2.html
/usr/share/gtk-doc/html/chafa/new-api-index-1.4.html
/usr/share/gtk-doc/html/chafa/new-api-index-1.6.html
/usr/share/gtk-doc/html/chafa/new-api-index-1.8.html
/usr/share/gtk-doc/html/chafa/right-insensitive.png
/usr/share/gtk-doc/html/chafa/right.png
/usr/share/gtk-doc/html/chafa/style.css
/usr/share/gtk-doc/html/chafa/up-insensitive.png
/usr/share/gtk-doc/html/chafa/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libchafa.so.0
/usr/lib64/libchafa.so.0.9.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/chafa/31a3d460bb3c7d98845187c716a30db81c44b615
/usr/share/package-licenses/chafa/7f11c0b5bfdf1146144bd11ce39af61c8296bc86
/usr/share/package-licenses/chafa/91664a5e5a2b5bf020a621d0e9c5cc507e619c94
/usr/share/package-licenses/chafa/a8a12e6867d7ee39c21d9b11a984066099b6fb6b
